[package]
name = "interstellar_os"
version = "0.1.0"
edition = "2021"

[build-dependencies]
bootloader = "0.11.3"
kernel = { path = "kernel", artifact = "bin", target = "x86_64-unknown-none" }
walkdir = "2.3.3"

[dependencies]
# used for UEFI booting in QEMU
ovmf-prebuilt = "0.1.0-alpha.1"

[workspace]
members = ["kernel"]

[profile.dev]
opt-level = 0
debug = true
panic = "abort"
 
[profile.release]
opt-level = 2
debug = false