name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3
    
    - name: Update
    - run: rustup update nightly && rustup default nightly
    - run: rustup component add llvm-tools-preview
    - run: cargo --version --verbose
    
    - name: Build
    - run: cargo build --verbose
    - run: cargo check --verbose
