name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3
      
    - name: Update
      run: rustup update && rustup update nightly && rustup default nightly
    
    - name: Add Target x86_64-unknown-none
      run: rustup target add x86_64-unknown-none
    
    - name: Add LLVM-Tools-Preview
      run: rustup component add llvm-tools-preview
      
    - name: Cargo Version
      run: cargo --version --verbose
      
    - name: Cargo config
      run: cargo -Z unstable-options config get
    
    - name: Build
      run: cargo build -Z bindeps --verbose
      
    - name: Check
      run: cargo check -Z bindeps --verbose
